services:
  django:
    build:
      context: ./
    restart: on-failure:5
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      - sh
      - -c
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate --noinput
        gunicorn -c gunicorn_config.py
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3-alpine
    container_name: ${DB_HOST}
    restart: on-failure:5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: on-failure:5
    ports:
      - "443:443"
    volumes:
      - ./static:/var/www/static
      - ./media:/var/www/media
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django
