name: heartbeat

heartbeat.monitors:
  - type: icmp
    id: ping-nginx
    name: Nginx Ping
    hosts: ["nginx"]
    schedule: '*/5 * * * * * *'

  - type: icmp
    id: ping-django
    name: Django Ping
    hosts: ["django"]
    schedule: '*/5 * * * * * *'

  - type: icmp
    id: ping-postgres
    name: Postgres Ping
    hosts: ["postgres"]
    schedule: '*/5 * * * * * *'

  - type: http
    schedule: "@every 5s"
    urls:
      - http://elasticsearch:9200
    username: heartbeat_internal
    password: ${HEARTBEAT_INTERNAL_PASSWORD}
    service.name: elk-service
    id: elk-id
    name: elk

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [http://elasticsearch:9200]
  username: heartbeat_internal
  password: ${HEARTBEAT_INTERNAL_PASSWORD}

http:
  enabled: true
  host: 0.0.0.0
