name: heartbeat

heartbeat.monitors:
  - type: tcp
    schedule: "@every 5s"
    hosts: ["localhost"]
    ports: [8000]
    service.name: ovelha-team-service
    id: ovelha-id
    name: ovelha

  - type: icmp
    id: ping-myhost
    name: My Host Ping
    hosts: ["localhost:8000"]
    schedule: '*/5 * * * * * *'

  - type: http
    schedule: "@every 5s"
    urls:
      - http://elasticsearch:9200
    username: heartbeat_internal
    password: ${HEARTBEAT_INTERNAL_PASSWORD}
    service.name: elk-service
    id: elk-id
    name: elk

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [http://elasticsearch:9200]
  username: heartbeat_internal
  password: ${HEARTBEAT_INTERNAL_PASSWORD}

http:
  enabled: true
  host: 0.0.0.0
