services:
  django:
    container_name: django
    build:
      context: ./django
    restart: on-failure:5
    ports:
      - "8000:8000"
    volumes:
      - ./django/static:/app/static
      - ./django/media:/app/media
      - ./django/logs:/app/logs
    networks:
      - net
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3-alpine
    container_name: ${DB_HOST}
    restart: on-failure:5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: on-failure:5
    ports:
      - "443:443"
    volumes:
      - ./django/static:/var/www/static
      - ./django/media:/var/www/media
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - net
    depends_on:
      - django

networks:
  net:
    driver: bridge

volumes:
  postgres:
